apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-config
  namespace: team-researchops
data:
  config.yaml: |
    data_source dataproducts:
      type: bigquery
      project_id: team-researchops-prod-01d6
      dataset: umami
